### ISSUE TITLE
race condition on local model parameters between computation and communication thread

### ISSUE THREAD

**Issue by XianzheMa** [DS3Lab/CocktailSGD#8]
Dear CocktailSGD authors:

I've been reading the CocktailSGD implementation these days, really great work thanks! I have a question on it:

CocktailSGD will update the (local) model parameters in its communication thread, for example [here](https://github.com/DS3Lab/CocktailSGD/blob/c0c490dcd2f7d1d6d279aadb797e8d52ff822eab/data_parallel/dist_dp_cocktail_sgd.py#L461). However this thread executes in parallel with the normal forward and backward pass, so it's possible that the forward pass does not use the original parameters, but the params having been updated by the communication thread to calculate output.

Does this have any influence/issue? Or do we somehow prevent this happening via a mechanism I overlooked?

Thanks a lot for answering my question.

Best,
Xianzhe

**Comment by LorrinWWW** [comment]
@XianzheMa Mixed-precision training involves using a fp16 (or bf16) copy for forward and backward passes, while the actual weight update takes place on a separate fp32 copy. The communication thread is responsible for transmitting the model differences and applying the communication update on the fp32 copy, which does not affect the results of the forward and backward computations that depends on the fp16 copy.
